services:
  rails:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: ''
        RAILS_ENV: 'development'
        RAILS_SERVE_STATIC_FILES: 'false'
    tty: true
    stdin_open: true
    image: shore:latest
    env_file: .env
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
      - vite_build:/app/public/vite-dev
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - VITE_RUBY_HOST=vite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
  solid_queue:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: ''
        RAILS_ENV: 'development'
        RAILS_SERVE_STATIC_FILES: 'false'
    tty: true
    stdin_open: true
    image: shore:latest
    env_file: .env
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules
      - vite_build:/app/public/vite-dev
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    depends_on:
      - postgres
      - rails
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
    command: ["bundle", "exec", "rake", "solid_queue:start"]
  vite:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: ''
        RAILS_ENV: 'development'
        RAILS_SERVE_STATIC_FILES: 'false'
    tty: true
    stdin_open: true
    image: shore:latest
    env_file: .env
    volumes:
      - ./:/app:delegated
      - node_modules:/app/node_modules # Node modules shared across containers
      - vite_build:/app/public/packs
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    ports:
      - 3036:3036
    depends_on:
      - rails  
    environment:
      - DEBUG='*vite*'
      - RAILS_ENV=development
      - VITE_RUBY_HOST=0.0.0.0
    entrypoint: docker/entrypoints/vite.sh
    command: bin/vite dev --clobber
  postgres:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=shore_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  postgres:
  vite_build:
  node_modules:
  cache:
  bundle: